@startuml

skinparam defaultFontSize 40        
skinparam SequenceMessageAlign center

actor User as User #40BFBF
boundary "LoginPage" as LoginPage #ffc327
boundary "ForgotPasswordPage" as FPPage #ffc327
boundary "EmailPage" as EmailPage #ffc327
boundary "NewPasswordPage" as NPPage #ffc327
control Router as Router #ff9045
control AuthController as AuthController #ff9045
entity AuthService as AuthService #ff9045
entity UserRepository as UserRepository #40bbb1
database MongoDB as DB #4CAF50

activate User #40BFBF
User -> LoginPage: click Forgot password
activate LoginPage #ffc327

LoginPage -> FPPage: redirect
deactivate LoginPage

User -> FPPage: input email
FPPage -> Router: POST /forgot-password
deactivate FPPage
activate Router #ff9045

Router -> AuthController: forgotPassword()
deactivate Router
activate AuthController #ff9045

AuthController -> AuthService: forgotPasswordRequest()
activate AuthService #ff9045

AuthService -> UserRepository: getByQuery(usr_email)
activate UserRepository #40bbb1

UserRepository -> DB: findOne(query)
activate DB #4CAF50

DB -> UserRepository: return foundedUser
deactivate DB

UserRepository -> AuthService: return foundedUser
deactivate UserRepository

AuthService -> AuthService: _checkUserStatus(foundedUser)
AuthService -> AuthService: generateTemporaryToken()

AuthService -> UserRepository: updateById()
activate UserRepository #40bbb1

UserRepository -> DB: findByIdAndUpdate(query)
activate DB #4CAF50

DB -> UserRepository: return updatedUser
deactivate DB

UserRepository -> AuthService: return updatedUser
deactivate UserRepository

alt#Gold #Pink User không được cập nhật
    AuthService -> AuthController: Failed to request password reset
    AuthController -> Router: Failed to request password reset
    activate Router #ff9045

    Router -> FPPage: Failed to request password reset
    deactivate Router
    activate FPPage #ffc327

    FPPage -> User: Failed to request password reset
    deactivate FPPage
else #LightBlue
    AuthService -> EmailPage: sendForgotPasswordEmail()
    AuthService -> AuthController: return result
    deactivate AuthService

    AuthController -> Router: Password reset email sent successfully
    activate Router #ff9045

    Router -> FPPage: Password reset email sent successfully
    activate FPPage #ffc327

    FPPage -> User: A reset password email...reset instructions
    deactivate FPPage

    User -> EmailPage: click Url
    activate EmailPage #ffc327

    EmailPage -> NPPage: redirect
    activate NPPage #ffc327

    User -> NPPage: input password
    NPPage -> Router: POST /reset-password
    deactivate NPPage
    activate Router #ff9045

    Router -> AuthController: resetPassword()
    deactivate Router
    activate AuthController #ff9045

    AuthController -> AuthService: resetForgottenPassword()
    activate AuthService #ff9045

    AuthService -> AuthService: hashToken()
    AuthService -> UserRepository: getByQuery(usr_email)
    activate UserRepository #40bbb1

    UserRepository -> DB: findOne(query)
    activate DB #4CAF50

    DB -> UserRepository: return foundedUser
    deactivate DB

    UserRepository -> AuthService: return foundedUser
    deactivate UserRepository

    AuthService -> AuthService: generateHashedPassword()
    AuthService -> UserRepository: updateById()
    activate UserRepository #40bbb1

    UserRepository -> DB: findByIdAndUpdate(query)
    activate DB #4CAF50

    DB -> UserRepository: return updatedUser
    deactivate DB

    UserRepository -> AuthService: return updatedUser
    deactivate UserRepository

    alt#Gold #Pink User không được cập nhật
        AuthService -> AuthController: Failed to reset password
        AuthController -> Router: Failed to reset password
        activate Router #ff9045

        Router -> FPPage: Failed to reset password
        deactivate Router
        activate FPPage #ffc327

        FPPage -> User: Failed to reset password
        deactivate FPPage
    else #LightBlue
        AuthService -> AuthController: return result
        deactivate AuthService

        AuthController -> Router: Password reset successfully
        activate Router #ff9045

        Router -> NPPage: Your password has...again
        deactivate Router
        activate NPPage

        NPPage -> LoginPage: redirect
        deactivate NPPage
        activate LoginPage
    end
end

@enduml